spring.application.name=Gateway
spring.cloud.compatibility-verifier.enabled=false
server.port=8080

politicsapp.members.url=${MEMBERS_SERVICE_URL:http://localhost:8081}
politicsapp.political-parties.url=${PARTIES_SERVICE_URL:http://localhost:8082}
politicsapp.gateway.host=${GATEWAY_HOST:localhost:8080}
