spring.application.name=Gateway
spring.cloud.compatibility-verifier.enabled=false
server.port=8080

rpg.members.url=http://localhost:8081
rpg.political-parties.url=http://localhost:8082
rpg.gateway.host=localhost:8080
